### ISSUE TITLE
list-repost doesn't show the correct number of files

### ISSUE THREAD

**Issue by fega** [pankajpatel/list-repos#1]
Only 0's and 1's

**Comment by pankajpatel** [comment]
yes, 0's and 1's for now. Though it will be good addition, let me create this feature.

Thanks for suggestions.

**Comment by pankajpatel** [comment]
please try to install by `npm i -g list-repos` and check. it should show the number as well.

**Comment by fega** [comment]
Hello again! 😄 

I [re]installed the repo a run it again, obtaining this:

![image](https://cloud.githubusercontent.com/assets/6069807/23832058/a636a9ca-06fb-11e7-8135-2f072e16b9a2.png)

All the repos are showing the number 1 instead the correct number of files
For example the "notes",
![image](https://cloud.githubusercontent.com/assets/6069807/23832070/e666ca5c-06fb-11e7-94d1-285ae3bfe477.png)

Also, you can see that in some repos where I don't have a remote repository yet is showing a green result and a NaN value.

**Comment by pankajpatel** [comment]
yes, thanks for your feedback; gotta check the issue.

Shows correct number here on linux based systems, though there might be issues with the Windows system.

**Comment by pankajpatel** [comment]
The Pull Request of the dependency library (https://github.com/watson/git-state/pull/8) will fix this.

**Comment by fega** [comment]
Ok, thanks :)

**Comment by pankajpatel** [comment]
The PR is merged now; please reinstall via `npm i -g list-repos`.

**Comment by fega** [comment]
I tested it, is solved 👍
